adal                                     1.2.7
adlfs                                    2024.2.0
aiohttp                                  3.9.3
aiosignal                                1.3.1
airflow-tools                            0.3.4
alembic                                  1.13.1
annotated-types                          0.6.0
anyio                                    3.7.1
apache-airflow                           2.8.3
apache-airflow-providers-amazon          8.17.0
apache-airflow-providers-common-io       1.3.1
apache-airflow-providers-common-sql      1.10.1
apache-airflow-providers-ftp             3.7.0
apache-airflow-providers-http            4.9.0
apache-airflow-providers-imap            3.5.0
apache-airflow-providers-microsoft-azure 8.5.1
apache-airflow-providers-smtp            1.6.1
apache-airflow-providers-sqlite          3.7.0
apispec                                  6.4.0
argcomplete                              3.2.2
arrow                                    1.3.0
asgiref                                  3.7.2
asn1crypto                               1.5.1
async-timeout                            4.0.3
attrs                                    23.2.0
azure-batch                              14.1.0
azure-common                             1.1.28
azure-core                               1.30.0
azure-cosmos                             4.5.1
azure-datalake-store                     0.0.53
azure-identity                           1.15.0
azure-keyvault-secrets                   4.7.0
azure-kusto-data                         4.3.1
azure-mgmt-containerinstance             10.1.0
azure-mgmt-containerregistry             10.3.0
azure-mgmt-core                          1.4.0
azure-mgmt-cosmosdb                      9.4.0
azure-mgmt-datafactory                   5.0.0
azure-mgmt-datalake-nspkg                3.0.1
azure-mgmt-datalake-store                0.5.0
azure-mgmt-nspkg                         3.0.2
azure-mgmt-resource                      23.0.1
azure-mgmt-storage                       21.1.0
azure-nspkg                              3.0.2
azure-servicebus                         7.11.4
azure-storage-blob                       12.19.0
azure-storage-file-datalake              12.14.0
azure-storage-file-share                 12.15.0
azure-synapse-artifacts                  0.18.0
azure-synapse-spark                      0.7.0
Babel                                    2.14.0
backoff                                  2.2.1
beautifulsoup4                           4.12.3
binaryornot                              0.4.4
blinker                                  1.7.0
boto3                                    1.34.38
boto3-stubs                              1.34.38
botocore                                 1.34.38
botocore-stubs                           1.34.38
build                                    1.0.3
CacheControl                             0.13.1
cachelib                                 0.9.0
certifi                                  2023.11.17
cffi                                     1.16.0
cfgv                                     3.4.0
chardet                                  5.2.0
charset-normalizer                       3.3.2
cleo                                     2.1.0
click                                    8.1.7
clickclick                               20.10.2
colorama                                 0.4.6
colorlog                                 4.8.0
ConfigUpdater                            3.2
connexion                                2.14.2
cookiecutter                             2.6.0
crashtest                                0.4.1
cron-descriptor                          1.4.3
croniter                                 2.0.1
cryptography                             41.0.7
Deprecated                               1.2.14
dill                                     0.3.8
distlib                                  0.3.8
dnspython                                2.5.0
docutils                                 0.20.1
dulwich                                  0.21.7
email-validator                          1.3.1
exceptiongroup                           1.1.3
fastapi                                  0.104.1
fastjsonschema                           2.19.1
filelock                                 3.13.1
Flask                                    2.2.5
Flask-AppBuilder                         4.3.11
Flask-Babel                              2.0.0
Flask-Caching                            2.1.0
Flask-JWT-Extended                       4.6.0
Flask-Limiter                            3.5.0
Flask-Login                              0.6.3
Flask-Session                            0.5.0
Flask-SQLAlchemy                         2.5.1
Flask-WTF                                1.2.1
frozenlist                               1.4.1
fsspec                                   2024.2.0
googleapis-common-protos                 1.62.0
google-re2                               1.1
graphviz                                 0.20.1
greenlet                                 3.0.3
grpcio                                   1.60.1
gunicorn                                 21.2.0
h11                                      0.14.0
httpcore                                 1.0.2
httpx                                    0.26.0
identify                                 2.5.35
idna                                     3.4
ijson                                    3.2.3
importlib-metadata                       6.11.0
importlib-resources                      6.1.1
inflection                               0.5.1
installer                                0.7.0
isodate                                  0.6.1
itsdangerous                             2.1.2
jaraco.classes                           3.3.0
jeepney                                  0.8.0
Jinja2                                   3.1.3
jmespath                                 1.0.1
jsonpath-ng                              1.6.1
jsonschema                               4.21.1
jsonschema-specifications                2023.12.1
keyring                                  24.3.0
lazy-object-proxy                        1.10.0
limits                                   3.7.0
line-profiler                            4.1.2
linkify-it-py                            2.0.3
lockfile                                 0.12.2
lxml                                     5.1.0
Mako                                     1.3.2
Markdown                                 3.5.2
markdown-it-py                           3.0.0
MarkupSafe                               2.1.5
marshmallow                              3.20.2
marshmallow-oneofschema                  3.1.0
marshmallow-sqlalchemy                   0.26.1
mdit-py-plugins                          0.4.0
mdurl                                    0.1.2
more-itertools                           10.1.0
msal                                     1.26.0
msal-extensions                          1.1.0
msgpack                                  1.0.7
msrest                                   0.7.1
msrestazure                              0.6.4
multidict                                6.0.5
nodeenv                                  1.8.0
numpy                                    1.26.4
oauthlib                                 3.2.2
opentelemetry-api                        1.22.0
opentelemetry-exporter-otlp              1.22.0
opentelemetry-exporter-otlp-proto-common 1.22.0
opentelemetry-exporter-otlp-proto-grpc   1.22.0
opentelemetry-exporter-otlp-proto-http   1.22.0
opentelemetry-proto                      1.22.0
opentelemetry-sdk                        1.22.0
opentelemetry-semantic-conventions       0.43b0
ordered-set                              4.1.0
Package                                  Version
packaging                                23.2
pandas                                   2.2.0
pandas-stubs                             2.1.4.231227
pathspec                                 0.12.1
pendulum                                 2.1.2
pexpect                                  4.9.0
pip                                      23.0.1
pkginfo                                  1.9.6
platformdirs                             3.11.0
pluggy                                   1.4.0
ply                                      3.11
poetry                                   1.7.1
poetry-core                              1.8.1
poetry-plugin-export                     1.6.0
portalocker                              2.8.2
pre-commit                               3.6.2
prison                                   0.2.1
protobuf                                 4.25.2
psutil                                   5.9.8
ptyprocess                               0.7.0
PyAthena                                 3.2.1
pycparser                                2.21
pydantic                                 2.5.1
pydantic_core                            2.14.3
Pygments                                 2.17.2
PyJWT                                    2.8.0
pyproject_hooks                          1.0.0
python-daemon                            3.0.1
python-dateutil                          2.8.2
python-nvd3                              0.15.0
python-slugify                           8.0.4
pytz                                     2024.1
pytzdata                                 2020.1
PyYAML                                   6.0.1
rapidfuzz                                3.6.1
redshift-connector                       2.0.918
referencing                              0.33.0
requests                                 2.31.0
requests-oauthlib                        1.3.1
requests-toolbelt                        1.0.0
rfc3339-validator                        0.1.4
rich                                     13.7.0
rich-argparse                            1.4.0
rpds-py                                  0.17.1
s3transfer                               0.10.0
scramp                                   1.4.4
SecretStorage                            3.3.3
setproctitle                             1.3.3
setuptools                               65.5.0
shellingham                              1.5.4
six                                      1.16.0
sniffio                                  1.3.0
soupsieve                                2.5
SQLAlchemy                               1.4.51
SQLAlchemy-JSONField                     1.0.2
sqlalchemy-redshift                      0.8.14
SQLAlchemy-Utils                         0.41.1
sqlparse                                 0.4.4
starlette                                0.27.0
tabulate                                 0.9.0
tenacity                                 8.2.3
termcolor                                2.4.0
text-unidecode                           1.3
toml                                     0.10.2
tomli                                    2.0.1
tomlkit                                  0.12.3
trove-classifiers                        2023.11.29
types-awscrt                             0.20.3
types-jmespath                           1.0.2.20240106
types-python-dateutil                    2.8.19.20240106
types-pytz                               2024.1.0.20240203
types-s3transfer                         0.10.0
types-toml                               0.10.8.7
typing_extensions                        4.8.0
tzdata                                   2023.4
uc-micro-py                              1.0.2
unicodecsv                               0.14.1
universal-pathlib                        0.1.4
urllib3                                  2.0.7
uvicorn                                  0.24.0.post1
virtualenv                               20.25.0
watchtower                               3.0.1
Werkzeug                                 2.2.3
wrapt                                    1.16.0
WTForms                                  3.1.2
yarl                                     1.9.4
zipp                                     3.17.0